import { ScenarioDefinition } from '../types/scenario';

export const SCENARIO_CATALOG: Record<string, ScenarioDefinition> = {
  LOW_BATTERY: {
    id: 'LOW_BATTERY',
    name: 'Depleted Battery Emergency',
    shortDesc: 'Rapid power depletion forcing low-power safeguard & recharge detour.',
    fullDesc: 'Simulates high electrical demand and battery reserve dropping below 15%. Triggers LOW_BATTERY hazard, forces operational mode to RECHARGE_STANDBY, and recalculates path to nearest solar haven.',
    expectedHazards: ['Low Battery Reserve', 'Anomalous Rapid Power Drain'],
    expectedRiskLevel: 'CRITICAL',
    suggestedMitigation: 'Cut power to scientific instruments, orient towards Solis Plateau Recharge Station, and halt night locomotion.',
    icon: 'BatteryWarning',
  },
  ROVER_STUCK: {
    id: 'ROVER_STUCK',
    name: 'Loose Dune Sand Entrapment',
    shortDesc: 'Wheels immobilized in drift sand with 85% slip and stall currents.',
    fullDesc: 'Simulates rover driving into hidden Neretva soft drift sand. Slip ratio escalates to 88%, forward speed plummets to 0 m/s despite motor torque, motor current spikes to 11A.',
    expectedHazards: ['Locomotion Entrapment (Rover Stuck)', 'Excessive Wheel Slip'],
    expectedRiskLevel: 'CRITICAL',
    suggestedMitigation: 'Execute autonomous peristaltic rocker-bogie crab-walk sequence; oscillate wheel directions; reverse track by 2 meters.',
    icon: 'AlertOctagon',
  },
  COMM_LOSS: {
    id: 'COMM_LOSS',
    name: 'Orbiter Loss-of-Signal (LOS)',
    shortDesc: 'Severe RF blackout and packet drop; autonomous safeguard takeover.',
    fullDesc: 'Simulates entry into canyon shadow or high-gain antenna tracking failure. Signal attenuates to -116 dBm with 98% packet loss. Proves the rover can operate safely without Earth teleoperation commands.',
    expectedHazards: ['Weak Communication Link / Comm Loss'],
    expectedRiskLevel: 'HIGH',
    suggestedMitigation: 'Switch to Full Autonomous Safeguard Mode (ASM); buffer all telemetry; steer to nearest high-elevation crest.',
    icon: 'WifiOff',
  },
  EXTREME_TEMP: {
    id: 'EXTREME_TEMP',
    name: 'Drive Actuator Thermal Runaway',
    shortDesc: 'Continuous drive slope friction raises motor assembly temp above 70°C.',
    fullDesc: 'Simulates mechanical friction overload in drive gearbox during uphill climb. Motor temperature spikes to 74°C, triggering thermal dissipation alerts and automated cooling protocol.',
    expectedHazards: ['Subsystem Thermal Overheating'],
    expectedRiskLevel: 'CRITICAL',
    suggestedMitigation: 'Halt vehicle locomotion; deploy thermal louvers; wait for motor winding temperature to fall below 45°C.',
    icon: 'Flame',
  },
  SOLAR_DUST: {
    id: 'SOLAR_DUST',
    name: 'Martian Dust Storm Deposition',
    shortDesc: 'Atmospheric regolith dust covers arrays, dropping solar efficiency to 20%.',
    fullDesc: 'Simulates a sudden localized dust devil depositing fine ferric dust across photovoltaic panels. Solar efficiency drops from 88% down to 22%, severely shrinking daily energy margin.',
    expectedHazards: ['Solar Panel Dust Deposition'],
    expectedRiskLevel: 'MODERATE',
    suggestedMitigation: 'Adjust panel gimbal angle toward direct sun vector; suspend high-draw spectral scans; stand by for wind clearing.',
    icon: 'SunDim',
  },
  HAZARDOUS_TERRAIN: {
    id: 'HAZARDOUS_TERRAIN',
    name: 'Belva Crater Scarp Incline',
    shortDesc: 'Rover encounters 27° steep slope with loose rock and rollover risk.',
    fullDesc: 'Simulates rover encountering steep crater rim scree. Slope exceeds safe 20° limit, roughness reaches 0.92, chassis pitch reaches 14°, triggering emergency brake and detour planning.',
    expectedHazards: ['Hazardous Terrain (Slope / Roughness)', 'Excessive Wheel Slip'],
    expectedRiskLevel: 'HIGH',
    suggestedMitigation: 'Apply mechanical parking brakes; synthesize 3D stereo point cloud; compute safe contour-following detour spline.',
    icon: 'Mountain',
  },
};
